services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n-np50.onrender.com   # ← 改成你實際的 Render domain
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: https://n8n-np50.onrender.com
      - key: N8N_ENCRYPTION_KEY
        value: l1gqYDW4NGT3O8pA6T6+tiQm5FERbdsJEsaUp4lP2Yk=
      - key: GENERIC_TIMEZONE
        value: Asia/Taipei
    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
      sizeGB: 1
